---

- name: Install Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - gnupg
    - bash-completion
    - net-tools
    - curl
    - lynx
    - vim

...
