---

- name: Install Where-Ever Root CA crt
  ansible.builtin.copy:
    src: "{{ certs }}"
    dest: "/usr/local/share/ca-certificates/{{ certs }}"
    owner: root
    mode: "0755"
  notify: Update ca-certificates
  loop:
    - Where_Ever_Root_CA_Root_CA_212425365443306115571426638685908456843.crt
  loop_control:
    loop_var: certs

...
