---

- name: Docker playbook
  hosts: all
  pre_tasks:
    - name: Verify ansible version
      ansible.builtin.assert:
        that: "ansible_version.full is version_compare('2.15', '>=')"
        msg: "Ansible 2.15 or later required"
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - docker
...
