kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-vault-0
  namespace: nfs-provisioning
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4096Mi
