---

- name: Update apt
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Download k8s key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"

- name: Add Kubernetes apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present

- name: Download helm key
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /etc/apt/keyrings/helm-apt-keyring.asc
    mode: "0644"
  when: "'k8s_controllers' in group_names"

- name: Add helm apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/helm-apt-keyring.asc] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
  when: "'k8s_controllers' in group_names"

- name: Download hashicorp key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp-keyring.asc
    mode: "0644"
  when: "'k8s_controllers' in group_names"

- name: Add hashicorp apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/hashicorp-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  when: "'k8s_controllers' in group_names"

- name: Run the equivalent of "apt-get update"
  ansible.builtin.apt:
    update_cache: true

...
