---

- name: Add argo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Deploy argo
  kubernetes.core.helm:
    name: argo
    release_namespace: argo
    chart_ref: argo/argo-cd
    create_namespace: true

# HA
# kubectl create namespace argocd
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.0/manifests/ha/install.yaml
...
