---

- name: Add argo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Deploy nfs-subdir-external-provisioner
  kubernetes.core.helm:
    name: argo
    release_namespace: argo
    chart_ref: argo/argo-cd
    create_namespace: true

...
