---

#curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.5.7/argo-linux-amd64.gz

# Unzip
#gunzip argo-linux-amd64.gz

# Make binary executable
#chmod +x argo-linux-amd64

# Move binary to path
#mv ./argo-linux-amd64 /usr/local/bin/argo

# Test installation
#argo version

#kubectl create namespace argo
#kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.7/install.yaml
#
...
