---

- name: Create control directory
  ansible.builtin.file:
    path: /var/opt/k8s
    state: directory
    mode: "0755"
    owner: root

- name: Include apt add repo tasks
  ansible.builtin.include_tasks:
    file: "apt_repos.yml"

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - kubectl
    - containerd
    - kubeadm
    - kubelet
    - apparmor-utils
    - python3-kubernetes
    - python3-jmespath
    - nfs-client

- name: Mark as hold
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubectl
    - kubelet
    - containerd

- name: Include containerd tasks
  ansible.builtin.include_tasks:
    file: "setup_containerd.yml"

- name: Check if k8s is initialised on controller
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: have_k8s_config
  when: "'k8s_controllers' in group_names"

- name: Include controller bootstrap
  ansible.builtin.include_tasks:
    file: "init_controllers.yml"
  when:
    - "'k8s_controllers' in group_names"
    - not have_k8s_config.stat.exists

- name: Check if k8s is initialised on workers
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: have_k8s_config
  when: "'k8s_nodes' in group_names"

- name: Include node bootstrap
  ansible.builtin.include_tasks:
    file: "init_nodes.yml"
  when:
    - "'k8s_nodes' in group_names"
    - not have_k8s_config.stat.exists

- name: Install helm
  ansible.builtin.package:
    name: helm
    state: present
  when: "'k8s_controllers' in group_names"

- name: Install tools on controllers
  ansible.builtin.include_tasks:
    file: "controller_tools.yml"
  when: "'k8s_controllers' in group_names"

- name: Remove taint from host
  kubernetes.core.k8s_taint:
    state: absent
    name: "{{ inventory_hostname }}"
    taints:
      - effect: NoSchedule
        key: "node-role.kubernetes.io/control-plane"
  when: "'k8s_controllers' in group_names"

- name: Process on Primary controller
  ansible.builtin.include_tasks:
    file: "primary_controller.yml"
  when: k8s_bootstrap_host == inventory_hostname

- name: Update bashrc for my settings
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - kubectl completion"
    block: |
      source <(kubectl completion bash)
  loop:
    - /root/.bashrc
    - /home/vikashb/.bashrc

# # kubeadm token list
#
# # Token CA Cert Hash
# # $ openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | \
# # openssl dgst -sha256 -hex | sed 's/^.* //'
#
# # kubectl get nodes
# # kubectl get pods --all-namespaces
#
# # kubectl run nginx --image nginx:latest
# # kubectl expose pod/nginx --port 80 --type NodePort
# # kubectl get services
#
...
