---

- name: Create the kube-flannel namespace
  kubernetes.core.k8s:
    name: kube-flannel
    api_version: v1
    kind: Namespace
    state: present
    definition:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged

- name: Add flannel repo
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: https://flannel-io.github.io/flannel

- name: Deploy flannel
  kubernetes.core.helm:
    name: flannel
    release_namespace: kube-flannel
    chart_ref: flannel/flannel
    set_values:
      - value: "podCidr={{ k8s_pod_cidr_nw }}"
        value_type: string

...
