---

- name: Get Join Command
  ansible.builtin.command: kubeadm token create --print-join-command --ttl=10m
  register: k8s_join
  delegate_to: "{{ k8s_bootstrap_host }}"
  changed_when: false
  when:
    - "'k8s' in group_names"
    - k8s_bootstrap_host != inventory_hostname

- name: Nodes join cluster if required
  ansible.builtin.command: >
    {{ k8s_join.stdout }}
  changed_when: false
  when:
    - "'k8s_nodes' in group_names"
    - k8s_bootstrap_host != inventory_hostname
    - not have_k8s_config.stat.exists

...
