---

- name: Include Roles
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - common_packages
    - bashrc
    - timezone
    - disable_swap

- name: Process OS Family Config
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

...
