---

- name: Add vault repo
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com

- name: Deploy vault
  kubernetes.core.helm:
    name: vault
    release_namespace: vault
    chart_ref: hashicorp/vault
    create_namespace: true

- name: Install packages
  ansible.builtin.package:
    name: vault
    state: present

# kubectl exec -ti <name of vault pod> -- vault operator init
# kubectl exec -ti <name of vault pod> -- vault operator unseal
#
...
