---

- name: Update bashrc for my settings
  ansible.builtin.blockinfile:
    path: "{{ files }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK -"
    block: |
      # set up tcsh like search
      bind '"\e[A": history-search-backward'
      bind '"\e[B": history-search-forward'

      # default editor
      export EDITOR=/usr/bin/vi
  loop:
    - /root/.bashrc
    - /home/vikashb/.bashrc
  loop_control:
    loop_var: files

- name: Update vimrc for my settings
  ansible.builtin.blockinfile:
    path: "{{ rcfile }}"
    marker: '" {mark} ANSIBLE MANAGED BLOCK -'
    block: |
      set nocompatible              " be iMproved, required
      filetype off                  " required

      colorscheme elflord
      set expandtab
      set shiftwidth=4
      set softtabstop=4
      set tabstop=4
      syntax on

      " Switch off all auto-indenting
      set nocindent
      set nosmartindent
      set noautoindent
      set indentexpr=
      filetype indent off
      filetype plugin indent off
    mode: "0644"
    owner: vikashb
    create: true
  loop:
    - /root/.vimrc
    - /home/vikashb/.vimrc
  loop_control:
    loop_var: rcfile

...
