---

- name: Update bashrc for my settings
  ansible.builtin.blockinfile:
    path: "{{ files }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK -"
    block: |
      # set up tcsh like search
      bind '"\e[A": history-search-backward'
      bind '"\e[B": history-search-forward'

      # default editor
      export EDITOR=/usr/bin/vi
  loop:
    - /root/.bashrc
    - /home/vikashb/.bashrc
  loop_control:
    loop_var: files

...
