---

- name: Include common roles
  ansible.builtin.include_role:
    name: "{{ files }}"
  loop:
    - bashrc
    - common_packages
    - timezone
  loop_control:
    loop_var: files

- name: Process OS Family Config
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

...
