---

- name: Include Roles
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - common_packages
    - bashrc
    - timezone
    - sudo
    - resolved
    - add_root_ca
    - firewall
  tags: initial_run 

- name: Set controller based facts
  ansible.builtin.set_fact:
    k3s_is_controller: true
    k3s_in_cluster: "{{ item.0.name }}"
    k3s_bootstrap_host: "{{ item.0.bootstrap.node }}"
    k3s_bootstrap_ip: "{{ item.0.bootstrap.ip }}"
    k3s_tls_san: "{{ item.0.tls_san.node }}"
    k3s_tls_san_ip: "{{ item.0.tls_san.ip }}"
    k3s_ips: "{{ item.0.ips }}"
    k3s_networks: "{{ item.0.networks }}"
  loop: "{{ k3s_clusters | subelements('controllers') }}"
  when: "item.1 == inventory_hostname"

- name: Set node based facts
  ansible.builtin.set_fact:
    k3s_is_node: true
    k3s_in_cluster: "{{ item.0.name }}"
    k3s_bootstrap_host: "{{ item.0.bootstrap.node }}"
    k3s_bootstrap_ip: "{{ item.0.bootstrap.ip }}"
    k3s_tls_san: "{{ item.0.tls_san.node }}"
    k3s_tls_san_ip: "{{ item.0.tls_san.ip }}"
    k3s_ips: "{{ item.0.ips }}"
    k3s_networks: "{{ item.0.networks }}"
  loop: "{{ k3s_clusters | subelements('nodes') }}"
  when:
    - "item.1 == inventory_hostname"
    - k3s_is_controller is sameas false

- name: Download helm key
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /etc/apt/keyrings/helm-apt-keyring.asc
    mode: "0644"
  when: k3s_is_controller is sameas true
  tags: initial_run 

- name: Add helm apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/helm-apt-keyring.asc] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
  when: k3s_is_controller is sameas true
  tags: initial_run 

- name: Run the equivalent of "apt-get update"
  ansible.builtin.apt:
    update_cache: true

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-kubernetes
    - python3-jmespath
    - nfs-client
    - apparmor-utils
    - jq
  tags: initial_run 

- name: Install keepalived
  ansible.builtin.package:
    name: keepalived
    state: present
  tags: initial_run 

- name: Install helm on controllers
  ansible.builtin.package:
    name: helm
    state: present
  when: k3s_is_controller is sameas true
  tags: initial_run 

- name: Install keepalive config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  when:
    - k3s_is_controller is sameas true
  tags: initial_run 

- name: Include Firewall rules
  ansible.builtin.include_tasks: "{{ k3s_firewalls[ansible_os_family] }}.yaml"
  tags: initial_run 

- name: Create control directory
  ansible.builtin.file:
    path: /var/opt/k3s
    state: directory
    mode: "0755"
    owner: root
  tags: initial_run 

- name: Create /etc/rancher/k3s
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"
    owner: root
  tags: initial_run 

- name: Enable mirroring of images from an upstream container registry
  ansible.builtin.copy:
    dest: /etc/rancher/k3s/registries.yaml
    content: |
      mirrors:
        "*":
        #docker.io:
        #registry.k8s.io:
    mode: "0644"
  tags: initial_run 

- name: Create k3s installer script
  ansible.builtin.copy:
    dest: /var/opt/k3s/k3s-installer.sh
    content: |
      #!/bin/bash
      mkdir -p /usr/local/bin
      cd /usr/local/bin
      curl -sfL https://get.k3s.io | \
        sh -s - server \
        --write-kubeconfig-mode=644 \
        --cluster-init \
        --embedded-registry \
        --disable=local-storage \
        --disable=servicelb \
        --tls-san={{ k3s_tls_san }} \
        --tls-san={{ k3s_tls_san_ip }}
      touch /var/opt/k3s/install.done
    mode: "0755"
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false

- name: Check if k3s is initialised on bootstrap host
  ansible.builtin.stat:
    path: /var/opt/k3s/install.done
  register: installation_done
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false

- name: Install k3s on bootstrap host
  ansible.builtin.command: /var/opt/k3s/k3s-installer.sh
  args:
    creates: /etc/containerd/config.toml
  changed_when: false
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false
    - not installation_done.stat.exists

- name: Wait for 6443/tcp on bootstrap node
  ansible.builtin.wait_for:
    host: "{{ k3s_bootstrap_host }}"
    port: 6443
    delay: 2

- name: Get Token from bootstrap node
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  delegate_to: "{{ k3s_bootstrap_host }}"
  changed_when: false
  when: "k3s_bootstrap_host != inventory_hostname"

- name: Create the controller join script
  ansible.builtin.copy:
    dest: /var/opt/k3s/k3s-installer.sh
    content: |
      #!/bin/bash
      mkdir -p /usr/local/bin
      cd /usr/local/bin
      curl -sfL https://get.k3s.io | \
        K3S_TOKEN={{ k3s_token.stdout }} sh -s - server \
        --server https://{{ k3s_bootstrap_host }}:6443 \
        --write-kubeconfig-mode=644 \
        --embedded-registry \
        --disable=local-storage \
        --disable=servicelb \
        --tls-san={{ k3s_tls_san }} \
        --tls-san={{ k3s_tls_san_ip }}
      touch /var/opt/k3s/install.done
    mode: "0755"
  when:
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false
    - "k3s_bootstrap_host != inventory_hostname"

- name: Create the node join script
  ansible.builtin.copy:
    dest: /var/opt/k3s/k3s-installer.sh
    content: |
      #!/bin/bash
      mkdir -p /usr/local/bin
      cd /usr/local/bin
      curl -sfL https://get.k3s.io | \
        K3S_TOKEN={{ k3s_token.stdout }} sh -s - agent \
        --server https://{{ k3s_bootstrap_host }}:6443
      touch /var/opt/k3s/install.done
    mode: "0755"
  when:
    - k3s_is_controller is sameas false
    - k3s_is_node is sameas true
    - "k3s_bootstrap_host != inventory_hostname"

- name: Check if k3s is initialised
  ansible.builtin.stat:
    path: /var/opt/k3s/install.done
  register: installation_done
  when: "k3s_bootstrap_host != inventory_hostname"

- name: Install k3s
  ansible.builtin.command: /var/opt/k3s/k3s-installer.sh
  args:
    creates: /etc/containerd/config.toml
  changed_when: false
  when:
    - "k3s_bootstrap_host != inventory_hostname"
    - not installation_done.stat.exists

- name: add helm repos
  kubernetes.core.helm_repository:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - name: metallb
      url: https://metallb.github.io/metallb
    - name: argocd
      url: https://argoproj.github.io/argo-helm
    - name: nfs-subdir-external-provisioner
      url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    - name: csi-driver-nfs
      url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false

- name: Deploy csi-driver-nfs
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name:  csi-driver-nfs
    release_namespace: kube-system
    chart_ref: csi-driver-nfs/csi-driver-nfs
    create_namespace: true
    wait: true
    values:
      storageClass:
        create: true
        name: nfs-csi
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
        parameters:
          server: "{{ k3s_nfs.server }}"
          share: "{{ k3s_nfs.path }}"
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false

- name: Deploy metallb
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: metallb
    release_namespace: metallb-system
    chart_ref: metallb/metallb
    create_namespace: true
    wait: true
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false

- name: Wait for 7472/tcp on bootstrap node
  ansible.builtin.wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 7472
    delay: 10

- name: Create IPAddressPool file
  ansible.builtin.copy:
    dest: /var/opt/k3s/IPAddressPool.yaml
    content: |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default
        namespace: metallb-system
      spec:
        addresses:
          - "{{ k3s_networks.lb_pool }}"
    mode: "0644"
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false

- name: Create L2Advertisement
  ansible.builtin.copy:
    dest: /var/opt/k3s/L2Advertisement.yaml
    content: |
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2-advert
        namespace: metallb-system
    mode: "0644"
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false

- name: Apply metallb values to the cluster.
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    src: "/var/opt/k3s/{{ item }}"
  loop:
    - IPAddressPool.yaml
    - L2Advertisement.yaml
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false

- name: Install k3s
  ansible.builtin.command: /var/opt/k3s/k3s-installer.sh
  args:
    creates: /etc/containerd/config.toml
  changed_when: false
  when:
    - "k3s_bootstrap_host != inventory_hostname"
    - not installation_done.stat.exists

- name: Clone gitops repo
  ansible.builtin.git:
    repo: https://github.com/vikashb72/gitops.git
    dest: /tmp/gitops
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false

- name: Install argocd
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    update_repo_cache: true
    dependency_update: true
    name: argocd
    chart_ref: /tmp/gitops/charts/argo-cd
    create_namespace: true
    release_namespace: argocd
    values_files:
      - /tmp/gitops/charts/argo-cd/values-{{ k3s_in_cluster }}.yaml
    wait: true

- name: Check if argocd binary is installed on controllers
  ansible.builtin.stat:
    path: /var/opt/k3s/argo_installed.done
  register: argo_installed
  when:
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false
- name: Install argocd binary on controllers
  ansible.builtin.command: /var/opt/k3s/argocd.project.sh
  args:
    creates: /var/opt/k3s/argo_installed.done
  changed_when: false
  when:
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false
    - not argo_installed.stat.exists

- name: Create argocd project definition
  ansible.builtin.copy:
    dest: /var/opt/k3s/argocd.project.yaml
    content: |
      metadata:
        name: {{ k3s_in_cluster }}
        namespace: argocd
      spec:
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
        destinations:
          - namespace: '*'
            server: '*'
        sourceRepos:
          - '*'
    mode: "0644"
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false
    - not argo_installed.stat.exists

- name: Install argocd binary
  ansible.builtin.copy:
    dest: /var/opt/k3s/argocd.project.sh
    content: |
      #!/usr/bin/env bash
      [ -f /usr/local/bin/argocd ] && exit 0
      VERSION=$(curl -L -s https://raw.githubusercontent.com/argoproj/argo-cd/stable/VERSION)
      curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v$VERSION/argocd-linux-amd64
      install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
      rm argocd-linux-amd64
      touch /var/opt/k3s/argo_installed.done
    mode: "0755"
  when:
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false
    - not argo_installed.stat.exists

- name: Install argocd binary
  ansible.builtin.copy:
    dest: /var/opt/k3s/create.argocd.project.sh
    content: |
      #!/usr/bin/env bash
      /usr/local/bin/argocd login $(kubectl get service argocd-server -n argocd --output=jsonpath='{.status.loadBalancer.ingress[0].ip}') --username admin --password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo) --insecure
      /usr/local/bin/argocd proj create {{ k3s_in_cluster }} -f /var/opt/k3s/argocd.project.yaml
      helm template /tmp/gitops/umbrella-chart/{{ k3s_in_cluster }} | kubectl -n argocd apply -f -
    mode: "0755"
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false
    - not argo_installed.stat.exists

- name: Install argocd binary on controllers
  ansible.builtin.command: /var/opt/k3s/argocd.project.sh
  args:
    creates: /var/opt/k3s/argo_installed.done
  changed_when: false
  when:
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false
    - not argo_installed.stat.exists

- name: Install argocd project
  ansible.builtin.command: /var/opt/k3s/create.argocd.project.sh
  args:
    creates: /var/opt/k3s/argo_project.done
  changed_when: false
  when:
    - "k3s_bootstrap_host == inventory_hostname"
    - k3s_is_controller is sameas true
    - k3s_is_node is sameas false
    - not argo_installed.stat.exists

# new
#- name: Apply metallb values to the cluster.
#  kubernetes.core.k8s:
#    kubeconfig: /etc/rancher/k3s/k3s.yaml
#    state: present
#    src: "/var/opt/k3s/{{ item }}"
#  loop:
#    - IPAddressPool.yaml
#    - L2Advertisement.yaml
#  when:
#    - "k3s_bootstrap_host == inventory_hostname"
#    - k3s_is_controller is sameas true
#    - k3s_is_node is sameas false
##- name: Create memberlist secret for metallb
##  ansible.builtin.command: >
##    kubectl create secret generic -n metallb-system metallb-memberlist
#    --from-literal=secretkey="$(openssl rand -base64 128)"
#  register: create_secret
#  changed_when: create_secret.rc == 0
#  when:
#    - "k3s_bootstrap_host == inventory_hostname"
#    - k3s_is_controller is sameas true
#    - k3s_is_node is sameas false

...
