---

# Allow Inbound

- name: Allow nodes and controllers to access Kubernetes API Server
  community.general.ufw:
    rule: allow
    proto: tcp
    port: 6443
    src: "{{ item }}"
  loop: "{{ k3s_ips.controllers + k3s_ips.nodes }}"

- name: Allow pods and services networks
  community.general.ufw:
    rule: allow
    src: "{{ item }}"
  loop:
    - "{{ k3s_networks.pods }}"
    - "{{ k3s_networks.services }}"

- name: Required only for HA with embedded etcd
  community.general.ufw:
    rule: allow
    proto: tcp
    port: 2379,2380
    src: "{{ item }}"
  loop: "{{ k3s_ips.controllers }}"

- name: Allow nodes and controllers to access Flannel VXLAN
  community.general.ufw:
    rule: allow
    proto: udp
    port: 8472
    src: "{{ item }}"
  loop: "{{ k3s_ips.controllers + k3s_ips.nodes }}"

- name: Allow nodes and controllers to access Kubelet metrics
  community.general.ufw:
    rule: allow
    proto: tcp
    port: 10250
    src: "{{ item }}"
  loop: "{{ k3s_ips.controllers + k3s_ips.nodes }}"

- name: Allow nodes and controllers to access Flannel Wireguard
  community.general.ufw:
    rule: allow
    proto: udp
    port: "51820,51821"
    src: "{{ item }}"
  loop: "{{ k3s_ips.controllers + k3s_ips.nodes }}"

- name: Allow nodes and controllers to access embedded distributed registry
  community.general.ufw:
    rule: allow
    proto: tcp
    port: 5001
    src: "{{ item }}"
  loop: "{{ k3s_ips.controllers + k3s_ips.nodes }}"

- name: Allow nodes and controllers to access metallb tcp 7946,7472
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "7472,7946"
    src: "{{ item }}"
  loop: "{{ k3s_ips.controllers + k3s_ips.nodes }}"

- name: Allow nodes and controllers to access metallb udp 7946,7472
  community.general.ufw:
    rule: allow
    proto: udp
    port: "7472,7946"
    src: "{{ item }}"
  loop: "{{ k3s_ips.controllers + k3s_ips.nodes }}"

- name: Allow nfs udp
  community.general.ufw:
    rule: allow
    proto: udp
    port: "111,911,878,674,2049,715"
    src: "{{ k3s_nfs.server }}"

- name: Allow nfs tcp
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "111,911,878,674,2049,715"
    src: "{{ k3s_nfs.server }}"

...
