---

- name: Install /etc/systemd/resolved.conf
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      DNS=192.168.0.4 192.168.0.1
      FallbackDNS=9.9.9.9
    owner: root
    mode: "0644"
  notify: Restart resolved

...
