---

k8s_nfs:
  server: 192.168.0.5
  path: /data/nfs

k3s_clusters:
  - name: dev
    bootstrap: k3s-dev-c1
    controllers:
      - k3s-dev-c1
      - k3s-dev-c2
      - k3s-dev-c3
    nodes:
      - k3s-dev-n1
      - k3s-dev-n2
      - k3s-dev-n3
    tls_san:
      - k3s-dev.home.where-ever.za.net
      - 192.168.0.30
  - name: prd
    bootstrap: k3s-prd-c1
    controllers:
      - k3s-prd-c1
      - k3s-prd-c2
      - k3s-prd-c3
    nodes:
      - k3s-prd-n1
      - k3s-prd-n2
      - k3s-prd-n3
    tls_san:
      - k3s-prd.home.where-ever.za.net

...
