---

k3s_firewalls:
  FreeBSD: pf
  Debian: ufw
  RedHat: firewalld

k3s_nfs:
  server: 192.168.0.3
  path: /data/nfs

k3s_clusters:
  - name: k3s
    networks:
      pods: 10.42.0.0/16
      services: 10.43.0.0/16
      lb_pool: "192.168.0.110-192.168.0.126"
    bootstrap:
      node: k3s-dev-c1
      ip: 192.168.0.31
    controllers:
      - k3s-dev-c1
      - k3s-dev-c2
      - k3s-dev-c3
    nodes:
      - k3s-dev-n1
      - k3s-dev-n2
      - k3s-dev-n3
    ips:
      controllers:
        - 192.168.0.31
        - 192.168.0.32
        - 192.168.0.33
      nodes:
        - 192.168.0.34
        - 192.168.0.35
        - 192.168.0.36
    tls_san:
      node: k3s-dev.home.where-ever.za.net
      ip: 192.168.0.30
  - name: prd
    networks:
      pods: 10.42.0.0/16
      services: 10.43.0.0/16
    bootstrap:
      node: k3s-prd-c1
      ip: 192.168.0.41
    controllers:
      - k3s-prd-c1
      - k3s-prd-c2
      - k3s-prd-c3
    nodes:
      - k3s-prd-n1
      - k3s-prd-n2
      - k3s-prd-n3
    ips:
      controllers:
        - 192.168.0.41
        - 192.168.0.42
        - 192.168.0.43
      nodes:
        - 192.168.0.44
        - 192.168.0.45
        - 192.168.0.46
    tls_san:
      node: k3s-prd.home.where-ever.za.net
      ip: 192.168.0.40

...
