---

k3s_firewalls:
  FreeBSD: pf
  Debian: ufw
  RedHat: firewalld

k3s_nfs:
  server: 192.168.0.3
  path: /data/nfs

k3s_clusters:
  - name: k3s
    networks:
      pods: 10.42.0.0/16
      services: 10.43.0.0/16
      lb_pool: "192.168.0.37-192.168.0.49"
    bootstrap:
      node: server-1.k3s.where-ever.net
      ip: 192.168.0.31
    controllers:
      - server-1.k3s.where-ever.net
      - server-2.k3s.where-ever.net
      - server-3.k3s.where-ever.net
    nodes:
      - agent-1.k3s.where-ever.net
      - agent-2.k3s.where-ever.net
      - agent-3.k3s.where-ever.net
    ips:
      controllers:
        - 192.168.0.31
        - 192.168.0.32
        - 192.168.0.33
      nodes:
        - 192.168.0.34
        - 192.168.0.35
        - 192.168.0.36
    tls_san:
      node: cluster.k3s.where-ever.net
      ip: 192.168.0.30

...
