# This is a basic workflow to help you get started with Actions

name: Ansible Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    # runs-on: ubuntu-latest
    # runs-on: [arc-runner-set-45kw8-runner-c47wk]
    #runs-on: [self-hosted]
    runs-on:  gh-arc-runners
    container:
      image: ubuntu:22.04
    steps:
      - name: update apt
        run: apt update
      - name: install pip3
        run: apt install python3-pip
      - name: Install ansible
        run: pip3 install --include-deps ansible ansible-lint
      - name: get ansible version
        run: ansible --version
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6 # or version tag instead of 'main'

