# This is a basic workflow to help you get started with Actions

name: Ansible Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    # runs-on: ubuntu-latest
    # runs-on: [arc-runner-set-45kw8-runner-c47wk]
    #runs-on: [self-hosted]
    runs-on: [self-hosted, linux]
    steps:
      - name: get ansible version
        run: ansible --version
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6 # or version tag instead of 'main'

