# This is a basic workflow to help you get started with Actions

name: GHA runner test

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: arc-runner-set
    container:
      image: ttl.sh/b-23-cdc2-2100-4e43-b86d-7aa714de3830:4h
    steps:
    
      - uses: actions/checkout@v4

      - name: debug
        run: |
          buildah unshare cat /proc/self/uid_map
          buildah --storage-driver vfs version
          buildah --storage-driver vfs info

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        id: buildah-build-image
        with:
          image: ttl.sh/85aaf77f-0573-4693-8f27-a58b2f06c7e8
          tags: ttl.sh/85aaf77f-0573-4693-8f27-a58b2f06c7e8:5m
          containerfiles: |
            ./Dockerfile
          build-args: |
            STAGE=production
          extra-args: |
            --storage-driver vfs
            --log-level debug
            --isolation chroot
