# This is a basic workflow to help you get started with Actions

name: GHA runner test

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: arc-runner-set
    steps:
    
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "one line"
        
