# This is a basic workflow to help you get started with Actions

name: GHA runner test

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  archive:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4

      - name: Create tarball
        run: |
          mkdir -p ../dist
          git archive --format=tar.gz -o repo.tgz \
             --prefix=${{ github.ref_name }} ${{ github.ref_name }}
          ls -l

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: "{{ github.ref_name }}_tarball"
          path: repo.tgz

  build:
    need: archive
    runs-on: arc-runner-set
    #runs-on: gcr.io/kaniko-project/executor:v1.20.0-debug
    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: "{{ github.ref_name }}_tarball"

      - name: Debug
        run:
          ls 
      #- name: Build images
      #  run: |
      #    /kaniko/executor \
      #    --context $CI_PROJECT_DIR
      #    --no-push
      #    --skip-unused-stages=true
      #    --cache=true
      #    --cache-repo=${CI_REGISTRY_IMAGE}/cache
      #    --log-timestamp=true
      #    --log-format=text
      #    --target build-and-test
      #    --verbosity=debug
      #    --build-arg NPM_TOKEN=${NPM_TOKEN}

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: "{{ github.ref_name }}_tarball"

