# This is a basic workflow to help you get started with Actions

name: GHA runner test

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  archive:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4

      - name: Create tarball
        run: |
          mkdir -p ../dist
          git archive --format=tar.gz -o repo.tgz \
             --prefix=${{ github.ref_name }} ${{ github.ref_name }}
          ls -l

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.ref_name }}_tarball"
          path: repo.tgz

  build:
    needs: archive
    #runs-on: arc-runner-set
    runs-on: ubuntu-latest
    container: 
      image: gcr.io/kaniko-project/executor:debug
    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: "${{ github.ref_name }}_tarball"

      - name: Build images
        run: |
          /kaniko/executor \
          --verbosity debug \
          --dockerfile Dockerfile \
          --context repo.tgz \
          --no-push \
          --build-arg STAGE=production
          --destination ttl.sh/4320e7b9-fd05-4bb0-b723-b12f3adedd7d:5m
          #--cache=true
          #--cache-repo=${CI_REGISTRY_IMAGE}/cache

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: "{{ github.ref_name }}_tarball"

